### ISSUE TITLE
Video is not detected when next video is auto played on Coursera.

### ISSUE THREAD

**Issue by shuowu** [shuowu/yi-note#42]
YiNote should be able to detect video change on Coursera, then reload states.

**Comment by shuowu** [comment]
@zhenwei2972 An option to reload tab when URL change has been added in the latest version 1.4.0. You can enable that option then add the domain, like coursera.org, you want to watch on. YiNote should be able to reload the tab when coursera's URL changes (play next video). Please update the extension and let me know if the issue has been fixed. 

Close this ticket, please reopen if the issue still exists.

**Comment by zhenwei2972** [comment]
Hi, i tried adding coursera.org and www.coursera.org, open and close the browser, with YiNote 1.4, it does not seem to perform the reload. might want to re-open?

**Comment by shuowu** [comment]
@zhenwei2972 can u provide the coursera link that can reproduce the issue? thanks

**Comment by zhenwei2972** [comment]
Hi @shaowu I was doing the coursera course C++ for C programmers 
https://www.coursera.org/learn/c-plus-plus-a/lecture/DmEwQ/3-8-print-chaining 
You might need a registered account to test.
 I have also done a Steps Recording using windows 10 new "Steps Recording" software, you can open and view slide show, with screenshots and annotated repro steps 
[reprosteps.zip](https://github.com/shuowu/yi-note/files/4832359/reprosteps.zip)

**Comment by shuowu** [comment]
Looks like it need a bit investigation to reach a general solution for static URL reload ... 
@zhenwei2972 For now I would suggest just reload the page when you want to take notes when URL change as a workaround.

**Comment by shuowu** [comment]
wait, reload is even not needed. Reload is added mostly to handle issues here: https://github.com/shuowu/yi-note#faqs
In Coursera page, it should work properly by just resetting current UI states. https://github.com/shuowu/yi-note/blob/master/extension/src/ui/containers/App/index.js#L54

I thought it was already handled, will make the change in the next release.

**Comment by zhenwei2972** [comment]
alright, that works for me , thanks for investigating!

**Comment by shuowu** [comment]
fixed in https://github.com/shuowu/yi-note/commit/fdbb06a8e7b2d66d5a3242877e99292919776fca

@zhenwei2972 please verify in latest version 1.4.1

**Comment by zhenwei2972** [comment]
Hi shuowu, 

Apologies but the issue still persists, I have made a video trying to show the repro steps more clearly with voice over. 
https://1drv.ms/v/s!Ap6TAbELY5u8h-Ny-F7Zy2RXG5xoyQ?e=meStN2

thanks for continually working on this issue!

**Comment by shuowu** [comment]
@zhenwei2972 ic, the fix handled the notes states but not the player instance when url change. I’ll make another update soon.

Thanks for the repro video!
